kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elasticsearch
  namespace: smartcommute-2020
  selfLink: >-
    /apis/route.openshift.io/v1/namespaces/smartcommute-2020/routes/elasticsearch
  uid: 65391929-86f4-11ea-836d-0a580a80010f
  resourceVersion: '57918'
  creationTimestamp: '2020-04-25T12:58:01Z'
  labels:
    io.kompose.service: elasticsearch
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: elasticsearch-smartcommute-2020.apps-crc.testing
  subdomain: ''
  to:
    kind: Service
    name: elasticsearch
    weight: 100
  port:
    targetPort: '9200'
  wildcardPolicy: None
status:
  ingress:
    - host: elasticsearch-smartcommute-2020.apps-crc.testing
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2020-04-25T12:58:01Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps-crc.testing
