kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: user-service
  namespace: smartcommute-2020
  selfLink: /apis/route.openshift.io/v1/namespaces/smartcommute-2020/routes/user-service
  uid: 7afcc99b-87a4-11ea-aa0b-0a580a800173
  resourceVersion: '65044'
  creationTimestamp: '2020-04-26T09:58:29Z'
  labels:
    io.kompose.service: user-service
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: user-service-smartcommute-2020.apps-crc.testing
  subdomain: ''
  to:
    kind: Service
    name: user-service
    weight: 100
  port:
    targetPort: '1339'
  wildcardPolicy: None
status:
  ingress:
    - host: user-service-smartcommute-2020.apps-crc.testing
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2020-04-26T09:58:30Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps-crc.testing

