apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    generation: null
    importPolicy: {}
    name: 7.0.0
status:
  dockerImageRepository: ""
