apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9201"
    port: 9201
    targetPort: 9201
  selector:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}
