apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: obsidiandynamics/kafdrop
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
