apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    io.kompose.service: kafdrop
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafdrop
    spec:
      containers:
      - env:
        - name: JVM_OPTS
          value: -Xms32M -Xmx64M
        - name: KAFKA_BROKERCONNECT
          value: kafka-cluster:9093
        - name: SERVER_SERVLET_CONTEXTPATH
          value: /
        image: ' '
        name: kafdrop
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - kafdrop
      from:
        kind: ImageStreamTag
        name: kafdrop:latest
    type: ImageChange
status: {}
