apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: wurstmeister/kafka:2.12-2.2.1
    generation: null
    importPolicy: {}
    name: 2.12-2.2.1
status:
  dockerImageRepository: ""
