apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  replicas: 1
  selector:
    io.kompose.service: kafka-cluster
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-cluster
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kafka-cluster:9093,OUTSIDE://localhost:9092
        - name: KAFKA_CREATE_TOPICS
          value: live-topic:1:1,enrichment-topic:1:1,scoring-topic:1:1,matching-routes-topic:1:1,route-analytics-topic:1:1
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_LISTENERS
          value: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: LOG_DIR
          value: /tmp/logs
        image: ' '
        name: kafka-cluster
        ports:
        - containerPort: 9092
        - containerPort: 9093
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - kafka-cluster
      from:
        kind: ImageStreamTag
        name: kafka-cluster:2.12-2.2.1
    type: ImageChange
status: {}
