apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/kibana/kibana:7.0.0
    generation: null
    importPolicy: {}
    name: 7.0.0
status:
  dockerImageRepository: ""
