apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scoring-enrichment-service
  name: scoring-enrichment-service
spec:
  ports:
  - name: "1338"
    port: 1338
    targetPort: 1338
  selector:
    io.kompose.service: scoring-enrichment-service
status:
  loadBalancer: {}
