apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: r00ta/user-service-jvm:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
