apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
  - name: "1339"
    port: 1339
    targetPort: 1339
  selector:
    io.kompose.service: user-service
status:
  loadBalancer: {}
