name: Platform CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup env variables
      env: 
        HERE_APP_KEY: ${{ secrets.HERE_APP_KEY }}
        HERE_API_KEY: ${{ secrets.HERE_API_KEY }}
        BOOTSTRAP_SERVERS: ${{ secrets.BOOTSTRAP_SERVERS }}
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build services
      run: mvn -f platform/pom.xml clean package -DskipTests      
    - name: Build docker images
      run: ./pipelines/build-docker-images.sh
    - name: Run docker compose
      run: docker-compose -f deploy/docker-compose/docker-compose.yml up -d
    - name: wait until mongodb is responsive
      run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:27017)" != "200" ]]; do sleep 5; done' || false
    - name: add test user to mongodb
      run: mongo admin -u root -p password --host localhost:27017 < ./pipelines/add-mongo-user.js
    - name: Run integration tests
      run: mvn -f platform/pom.xml test
